language: python

sudo: required

dist: trusty

addons:
  apt:
    packages:
      - apt-get
      - install
      - build-essential
      - g++
      - flex
      - bison
      - gperf
      - ruby
      - perl
      - libsqlite3-dev
      - libfontconfig1-dev
      - libicu-dev
      - libfreetype6
      - libssl-dev
      - libpng-dev
      - libjpeg-dev
      - python
      - libx11-dev
      - libxext-dev

before_script:
  - git checkout 2.1.1
  - git submodule init
  - git submodule update

script:
  - python build.py
